import axios from 'axios';

const BACKEND_URL =
  'https://rncourse-expense-tracker-app-default-rtdb.firebaseio.com/';

export async function storeExpense(expenseData) {
  const response = await axios.post(
    BACKEND_URL + '/expenses.json',
    expenseData
  );
  const id = response.data.name; //firebase id is called 'name'
  return id;
}

export async function fetchExpenses() {
  // asynnc function -- will also return a promise, so when you use it, also call it async
  const response = await axios.get(BACKEND_URL + '/expenses.json');
  //for Firebase, this response will be an object with a data property
  // That data property is another object.
  // Each key in data is an id string generated by Firebase.
  // The corresponding value is the expense object you sent in.
  const expenses = [];

  for (const key in response.data) {
    const expenseObj = {
      id: key,
      amount: response.data[key].amount,
      date: new Date(response.data[key].date),
      description: response.data[key].description,
    };
    expenses.push(expenseObj);
  }
  return expenses;
}

export function updateExpense(id, expenseData) {
  return axios.put(BACKEND_URL + `expenses/${id}.json`, expenseData);
  //returns a promise
}

export function deleteExpense(id) {
  return axios.delete(BACKEND_URL + `expenses/${id}.json`);
  //returns a promise
}
